//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Baza1Entities : DbContext
    {
        public Baza1Entities()
            : base("name=Baza1Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
    
        public virtual int AdminDelete(Nullable<int> idAdmin)
        {
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("idAdmin", idAdmin) :
                new ObjectParameter("idAdmin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminDelete", idAdminParameter);
        }
    
        public virtual int AdminInsert(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminInsert", usernameParameter, passwordParameter);
        }
    
        public virtual int AdminUpdate(Nullable<int> idAdmin, string username, string password)
        {
            var idAdminParameter = idAdmin.HasValue ?
                new ObjectParameter("idAdmin", idAdmin) :
                new ObjectParameter("idAdmin", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdminUpdate", idAdminParameter, usernameParameter, passwordParameter);
        }
    }
}
